/**
 * Derived product taxonomy — normalizes the raw `size` field from
 * products.json into canonical filter values, and extracts color +
 * material from product names. All derived at read-time so
 * products.json stays untouched (it gets regenerated by the scraper).
 */

import type { Product } from "@/data/types";

/* ------------------------------------------------------------------ */
/* Size normalization                                                  */
/* ------------------------------------------------------------------ */

export type SizeBucket =
  /** Liquid volume in fluid ounces — drinkware. */
  | "oz"
  /** Two-axis dimension `W x H` — frames, journals, portfolios. */
  | "rect"
  /** Single linear measurement in inches. */
  | "inch"
  /** Diameter (cylindrical / circular items). */
  | "diam"
  /** Recognized format but doesn't fit any of the above. */
  | "other";

export interface NormalizedSize {
  raw: string;
  canonical: string;
  bucket: SizeBucket;
}

export function normalizeSize(raw: string | null | undefined): NormalizedSize | null {
  if (!raw) return null;
  const s = raw.trim().replace(/\.+$/, "");

  // oz volume
  const ozMatch = s.match(/^(\d+(?:\.\d+)?)\s*oz\.?$/i);
  if (ozMatch) {
    let n = ozMatch[1];
    if (n.endsWith(".0")) n = n.slice(0, -2);
    return { raw, canonical: `${n} oz`, bucket: "oz" };
  }

  if (/^[\d\s/.]+"\s*x\s*[\d\s/.]+"$/i.test(s)) {
    return { raw, canonical: s.replace(/\s*x\s*/i, " x "), bucket: "rect" };
  }

  const diamMatch = s.match(/^([\d\s/.]+)"\s*diameter$/i);
  if (diamMatch) {
    return { raw, canonical: `${diamMatch[1].trim()}" diameter`, bucket: "diam" };
  }

  if (/^[\d\s/.]+"$/i.test(s)) {
    return { raw, canonical: s, bucket: "inch" };
  }

  return { raw, canonical: s, bucket: "other" };
}

export function productSize(product: Product): NormalizedSize | null {
  return normalizeSize(product.size);
}

/* ------------------------------------------------------------------ */
/* Color extraction                                                    */
/*                                                                     */
/* Most products encode color in the name: "Royal Blue 12 oz. Powder   */
/* Coated Water Bottle", "Aluminum Cake Pan with Navy Blue Powder      */
/* Coated Lid". We match against a canonical-with-aliases list,        */
/* longest alias first so "Royal Blue" wins over "Blue".               */
/* ------------------------------------------------------------------ */

interface KeywordGroup {
  canonical: string;
  aliases: string[];
  /** Hex used in the swatch chip. `null` = leave the swatch unfilled
   *  (for combos / wood tones we don't pretend to render exactly). */
  swatch?: string | string[] | null;
}

const COLOR_GROUPS: KeywordGroup[] = [
  { canonical: "Black", aliases: ["Black", "Jet Black", "Matte Black", "Onyx"], swatch: "#0f0f0f" },
  { canonical: "White", aliases: ["White", "Pearl White"], swatch: "#fafafa" },
  { canonical: "Cream", aliases: ["Cream", "Ivory", "Off-White", "Sand"], swatch: "#f5e9c8" },
  { canonical: "Red", aliases: ["Red", "Cherry Red", "Crimson"], swatch: "#c33a2c" },
  { canonical: "Burgundy", aliases: ["Burgundy", "Maroon", "Wine"], swatch: "#5e1a1a" },
  { canonical: "Pink", aliases: ["Hot Pink", "Light Pink", "Pink", "Rose"], swatch: "#e879a5" },
  { canonical: "Coral", aliases: ["Coral", "Salmon"], swatch: "#fb6f5f" },
  { canonical: "Orange", aliases: ["Orange"], swatch: "#f06a2a" },
  { canonical: "Yellow", aliases: ["Yellow"], swatch: "#f0c83a" },
  { canonical: "Gold", aliases: ["Gold", "Champagne"], swatch: "#c8a04a" },
  { canonical: "Copper", aliases: ["Copper", "Rose Gold"], swatch: "#b56a3a" },
  { canonical: "Bronze", aliases: ["Bronze"], swatch: "#8a5a30" },
  { canonical: "Brown", aliases: ["Dark Brown", "Light Brown", "Chocolate", "Espresso", "Brown"], swatch: "#6a3f23" },
  { canonical: "Beige", aliases: ["Beige", "Khaki", "Tan", "Taupe"], swatch: "#c8ad84" },
  { canonical: "Olive", aliases: ["Olive"], swatch: "#6a6a30" },
  { canonical: "Green", aliases: ["Forest Green", "Hunter Green", "Sage Green", "Mint Green", "Lime", "Green"], swatch: "#2f7a3f" },
  { canonical: "Teal", aliases: ["Teal", "Turquoise"], swatch: "#2da6a0" },
  { canonical: "Blue", aliases: ["Royal Blue", "Navy Blue", "Light Blue", "Powder Blue", "Sky Blue", "Aqua Blue", "Blue"], swatch: "#2a5acf" },
  { canonical: "Purple", aliases: ["Purple", "Violet", "Lavender", "Plum"], swatch: "#7d3ad0" },
  { canonical: "Charcoal", aliases: ["Charcoal"], swatch: "#3a3a3a" },
  { canonical: "Gray", aliases: ["Slate Gray", "Slate Grey", "Gray", "Grey"], swatch: "#7a7a7a" },
  { canonical: "Silver", aliases: ["Silver"], swatch: "#c2c2c4" },
  { canonical: "Camo", aliases: ["Camo", "Camouflage"], swatch: ["#3a4a2a", "#6a6a40", "#3a3a2a"] },
];

const MATERIAL_GROUPS: KeywordGroup[] = [
  { canonical: "Aluminum", aliases: ["Aluminum", "Aluminium"], swatch: "#b0b3b5" },
  { canonical: "Stainless Steel", aliases: ["Stainless Steel", "Stainless"], swatch: "#9aa0a4" },
  { canonical: "Bamboo", aliases: ["Bamboo"], swatch: "#cfa15a" },
  { canonical: "Walnut", aliases: ["Walnut"], swatch: "#5a3924" },
  { canonical: "Cherry", aliases: ["Cherry Wood", "Cherry"], swatch: "#83432a" },
  { canonical: "Maple", aliases: ["Maple"], swatch: "#c79460" },
  { canonical: "Oak", aliases: ["Oak"], swatch: "#a06a3a" },
  { canonical: "Wood", aliases: ["Wood", "Rosewood", "Mahogany"], swatch: "#7a4a2a" },
  { canonical: "Leatherette", aliases: ["Leatherette"], swatch: "#7a5a3a" },
  { canonical: "Leather", aliases: ["Leather"], swatch: "#6a3f23" },
  { canonical: "Cork", aliases: ["Cork"], swatch: "#c8a06a" },
  { canonical: "Glass", aliases: ["Glass", "Crystal", "Glassware"], swatch: "#cfe5ef" },
  { canonical: "Acrylic", aliases: ["Acrylic"], swatch: "#dadada" },
  { canonical: "Resin", aliases: ["Resin"], swatch: "#bca48a" },
  { canonical: "Marble", aliases: ["Marble"], swatch: "#dad7c4" },
  { canonical: "Slate", aliases: ["Slate"], swatch: "#535a63" },
  { canonical: "Polar Camel", aliases: ["Polar Camel"], swatch: null },
];

interface KeywordIndex {
  alias: string;
  aliasLower: string;
  re: RegExp;
  canonical: string;
}

function buildKeywordIndex(groups: KeywordGroup[]): KeywordIndex[] {
  const flat: KeywordIndex[] = [];
  for (const g of groups) {
    for (const alias of g.aliases) {
      flat.push({
        alias,
        aliasLower: alias.toLowerCase(),
        re: new RegExp(`\\b${alias.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "i"),
        canonical: g.canonical,
      });
    }
  }
  flat.sort((a, b) => b.alias.length - a.alias.length);
  return flat;
}

const COLOR_INDEX = buildKeywordIndex(COLOR_GROUPS);
const MATERIAL_INDEX = buildKeywordIndex(MATERIAL_GROUPS);

function extractFirst(name: string, idx: KeywordIndex[]): string | null {
  for (const entry of idx) {
    if (entry.re.test(name)) return entry.canonical;
  }
  return null;
}

export function productColor(p: Product): string | null {
  return extractFirst(p.name, COLOR_INDEX);
}

export function productMaterial(p: Product): string | null {
  return extractFirst(p.name, MATERIAL_INDEX);
}

export function colorSwatch(canonical: string): string | string[] | null {
  const g = COLOR_GROUPS.find((g) => g.canonical === canonical);
  return g?.swatch ?? null;
}

/* ------------------------------------------------------------------ */
/* Facet types + builders                                              */
/* ------------------------------------------------------------------ */

export interface SizeFacet {
  bucket: SizeBucket;
  canonical: string;
  count: number;
}

export interface SimpleFacet {
  canonical: string;
  count: number;
  swatch?: string | string[] | null;
}

export interface SubcategoryFacet {
  slug: string;
  name: string;
  count: number;
}

/**
 * Build size facets, but with enterprise hygiene:
 *
 *   - `minCount`: hide any chip with fewer than N products. Defaults
 *     to 2 — a "filter" with one matching product is dead-end noise.
 *   - The "other" bucket (combo strings like `"2 oz. 2 3/8""`) is
 *     dropped from the UI entirely; it surfaces in counts/totals only.
 */
export function buildSizeFacets(
  products: Product[],
  { minCount = 2 }: { minCount?: number } = {},
): SizeFacet[] {
  const counts = new Map<string, SizeFacet>();
  for (const p of products) {
    const ns = productSize(p);
    if (!ns || ns.bucket === "other") continue;
    const key = `${ns.bucket}::${ns.canonical}`;
    const prev = counts.get(key);
    if (prev) prev.count += 1;
    else counts.set(key, { bucket: ns.bucket, canonical: ns.canonical, count: 1 });
  }
  const bucketRank: Record<SizeBucket, number> = {
    oz: 0, rect: 1, inch: 2, diam: 3, other: 4,
  };
  return [...counts.values()]
    .filter((f) => f.count >= minCount)
    .sort((a, b) => {
      const r = bucketRank[a.bucket] - bucketRank[b.bucket];
      if (r !== 0) return r;
      const an = parseFloat(a.canonical);
      const bn = parseFloat(b.canonical);
      if (!Number.isNaN(an) && !Number.isNaN(bn) && an !== bn) return an - bn;
      return a.canonical.localeCompare(b.canonical);
    });
}

export function buildColorFacets(
  products: Product[],
  { minCount = 2 }: { minCount?: number } = {},
): SimpleFacet[] {
  const counts = new Map<string, number>();
  for (const p of products) {
    const c = productColor(p);
    if (!c) continue;
    counts.set(c, (counts.get(c) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([canonical, count]) => ({ canonical, count, swatch: colorSwatch(canonical) }))
    .filter((f) => f.count >= minCount)
    .sort((a, b) => b.count - a.count || a.canonical.localeCompare(b.canonical));
}

export function buildMaterialFacets(
  products: Product[],
  { minCount = 2 }: { minCount?: number } = {},
): SimpleFacet[] {
  const counts = new Map<string, number>();
  for (const p of products) {
    const m = productMaterial(p);
    if (!m) continue;
    counts.set(m, (counts.get(m) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([canonical, count]) => ({ canonical, count }))
    .filter((f) => f.count >= minCount)
    .sort((a, b) => b.count - a.count || a.canonical.localeCompare(b.canonical));
}

export function buildSubcategoryFacets(products: Product[]): SubcategoryFacet[] {
  const counts = new Map<string, SubcategoryFacet>();
  for (const p of products) {
    const prev = counts.get(p.subcategorySlug);
    if (prev) prev.count += 1;
    else counts.set(p.subcategorySlug, {
      slug: p.subcategorySlug, name: p.subcategoryName, count: 1,
    });
  }
  return [...counts.values()].sort((a, b) => b.count - a.count);
}

/* ------------------------------------------------------------------ */
/* Smart per-page facet selection                                      */
/*                                                                     */
/* Different categories want different facets. Drinkware buyers want   */
/* "12 oz / 20 oz / 30 oz", not the bottle's HEIGHT (the inch facet    */
/* is just bottle-height for that subcategory and adds noise). Frames  */
/* buyers want "5x7 / 8x10", not the volume of nothing. This planner   */
/* picks a sensible subset based on what the data actually contains.   */
/* ------------------------------------------------------------------ */

export interface FacetPlan {
  showOz: boolean;
  showRect: boolean;
  showInch: boolean;
  showDiam: boolean;
  showColor: boolean;
  showMaterial: boolean;
}

export function planFacets(
  products: Product[],
  sizeFacets: SizeFacet[],
  colorFacets: SimpleFacet[],
  materialFacets: SimpleFacet[],
): FacetPlan {
  const total = products.length;
  const ozCovered = sizeFacets
    .filter((f) => f.bucket === "oz")
    .reduce((n, f) => n + f.count, 0);
  const rectCovered = sizeFacets
    .filter((f) => f.bucket === "rect")
    .reduce((n, f) => n + f.count, 0);
  const inchCovered = sizeFacets
    .filter((f) => f.bucket === "inch")
    .reduce((n, f) => n + f.count, 0);
  const diamCovered = sizeFacets
    .filter((f) => f.bucket === "diam")
    .reduce((n, f) => n + f.count, 0);

  // If oz is dominant (>30% of products), hide inches/diam — they're
  // just the bottle's height/circumference, not useful filters.
  const ozDominant = ozCovered / Math.max(1, total) > 0.3;

  return {
    showOz: ozCovered >= 2,
    showRect: rectCovered >= 4 && !ozDominant,
    showInch: inchCovered >= 4 && !ozDominant,
    showDiam: diamCovered >= 4 && !ozDominant,
    showColor: colorFacets.length >= 2,
    showMaterial: materialFacets.length >= 2,
  };
}

/* ------------------------------------------------------------------ */
/* Filtering                                                           */
/* ------------------------------------------------------------------ */

export function filterBySize(products: Product[], allowed: readonly string[]): Product[] {
  if (allowed.length === 0) return products;
  const set = new Set(allowed);
  return products.filter((p) => {
    const ns = productSize(p);
    return ns ? set.has(ns.canonical) : false;
  });
}

export function filterBySubcategory(products: Product[], allowed: readonly string[]): Product[] {
  if (allowed.length === 0) return products;
  const set = new Set(allowed);
  return products.filter((p) => set.has(p.subcategorySlug));
}

export function filterByColor(products: Product[], allowed: readonly string[]): Product[] {
  if (allowed.length === 0) return products;
  const set = new Set(allowed);
  return products.filter((p) => {
    const c = productColor(p);
    return c ? set.has(c) : false;
  });
}

export function filterByMaterial(products: Product[], allowed: readonly string[]): Product[] {
  if (allowed.length === 0) return products;
  const set = new Set(allowed);
  return products.filter((p) => {
    const m = productMaterial(p);
    return m ? set.has(m) : false;
  });
}
